### ISSUE TITLE
Support for jsonp

### ISSUE THREAD

**Issue by fireflyk** [moshen/logstash-http-input#10]
Is it supported jsonp?

I want to send ajax to the jetty server(logstash-http-input), but it cross domain.
So with jQuery, I choose to use jsonp pattern to send ajax request.
It need response content-type: application/x-javascript; charset=utf-8. 

Can I set it to the logstash-http-input?

**Comment by moshen** [comment]
This is a good question, and an interesting use-case for the plugin.  #6 proposed supporting `OPTIONS` calls (though they didn't respond on my question about usage) for CORS.  Again, my suggestion would be to use a [reverse proxy](http://nginx.com/resources/admin-guide/reverse-proxy/) in front of logstash-http-input to do more complex interactions (especially when exposing the service to untrusted clients).

While the goal behind the plugin is to keep it simple and  easy to use, adding support for setting the `Content-Type` could be easily implemented.

**Comment by maorshabo** [comment]
@moshen Can you please show us an example of how to do a reverse proxy in front of logstash-http-input please?

**Comment by moshen** [comment]
Some of the [nginx docs are an excellent introduction to the topic](https://www.nginx.com/resources/admin-guide/reverse-proxy/).  Also, [enable-cors.org](http://enable-cors.org/server_nginx.html) has some server-specific information on cors configurations.

Finally, to enable something like jsonp you can use the [nginx subs module](http://wiki.nginx.org/HttpSubsModule) to insert a jsonp callback function.  Something like this:

``` conf
location /log {
  subs_filter_types text/plain;
  subs_filter "^.*$" "${arg_jsonp}();" r;
  proxy_pass http://backend-logstash-server;
}
```

FYI, that isn't tested and is simply an example of something that can be achieved in an nginx config.
