### ISSUE TITLE
Add a servlet to the jetty server

### ISSUE THREAD

**Issue by fireflyk** [moshen/logstash-http-input#11]
Can I add a servlet to the jetty server?
Because I need some extension. I need write some logic in the servlet and return something.

**Comment by moshen** [comment]
This plugin isn't meant to act as a generic servlet container, merely an HTTP input to logstash.  What exactly is the workflow you're looking for?  If the idea is to operate on incoming log messages, I suggest implementing your logic as a filter plugin to be used in the typical logstash workflow.
