### ISSUE TITLE
How to make HTTP input plugin available to logstash? Is gem missing?

### ISSUE THREAD

**Issue by kwk** [moshen/logstash-http-input#12]
Hi,

I've followed [this guide](http://logstash.net/docs/1.4.0.rc1/extending/example-add-a-new-filter) to install a plugin in logstash with your http input. According to this  https://github.com/elastic/logstash/issues/3208 issue, it looks like your plugin is not implementing the new gem based architecture. Is that correct?

> --pluginpath becomes moot with the new ruby-gem based plugin system. Not deprecated, but moot. 
> That's why it has been removed.
>
> For more information about writing plugins, see the "How to write a Logstash input|output|filter|codec] 
> Plugin" pages at http://www.elastic.co/guide/en/logstash/current/index.html

This is how I've tried to make your plugin available to logstash:

```
docker run \
  -v "$PWD/logstash-http-input/dirToCopyTheContentsOfBuildTo:/logstash-plugins"  \
  -it \
  --rm \
  -v "$PWD/logstash/config-dir":/config-dir logstash \
    logstash \
      -f /config-dir/logstash.conf \
      --pluginpath /logstash-plugins
```

This should mount my local copy of your code (the build version) into the `/logstash-plugins` directory inside the container. But apparently the `--pluginpath` is deprecated. See for yourself:

```
Clamp::UsageError: Unrecognised option '--pluginpath'
  signal_usage_error at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:103
         find_option at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/option/parsing.rb:62
       parse_options at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/option/parsing.rb:28
               parse at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:52
                 run at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.2.2-java/lib/logstash/runner.rb:80
                call at org/jruby/RubyProc.java:271
                 run at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.2.2-java/lib/logstash/runner.rb:96
                call at org/jruby/RubyProc.java:271
          initialize at /opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/task.rb:12
```

Regards,
Konrad

**Comment by kwk** [comment]
I wonder if I really need your plugin, when it says that there already is an http plugin available: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html

**Comment by kwk** [comment]
The `http` input plugin works.

**Comment by moshen** [comment]
You are correct.  [The new http input plugin (which looks like it's based on puma)](https://github.com/logstash-plugins/logstash-input-http/blob/94149c95051065874825f3f72f693a953196329d/lib/logstash/inputs/http.rb), is new for logstash 1.5.0.  I made this plugin to get http input for logstash <= 1.4.x

I will make a note in the main project page.
