### ISSUE TITLE
Fails to parse json

### ISSUE THREAD

**Issue by ThomasdOtreppe** [moshen/logstash-http-input#13]
I use http input and output to forward the logs from one system to another.

The output works fairly well (aside from an easy bug to fix). On the other hand, the input plugin doesn't seem to like the directive codec and doesn't parse the logs accordingly.

Client configuration:

```
        http {
               format => "json"
                http_method => "post"
                url => "http://10.0.0.1:8080/"
```

Server configuration:

```
        http {
                threads => 10
               codec => "json"
        }
```

I made a packet capture to see what's going wrong and I can see the json is encoded correctly (validated) and the request is correct but I get 400 Bad request every single time. When I look on the server, I can see messages like this:

```
2015-07-30 15:27:55 -0600: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
2015-07-30 15:27:55 -0600: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:fd 2>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "CONTENT_TYPE"=>"text/plain", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"2.11.3", "GATEWAY_INTERFACE"=>"CGI/1.2", "REQUEST_METHOD"=>"POST"}
```

which seem to indicate that the input http doesn't take the codec into account when decoding. 

Disabling json on both sides fixes the issue.

**Comment by moshen** [comment]
I'm guessing you're using the [official http input for logstash 1.5.x](https://github.com/logstash-plugins/logstash-input-http) as this one doesn't expose `threads` as a configuration option.

**Comment by ThomasdOtreppe** [comment]
How is it related to my issue? And second, if it's not exposed, why is it in the documentation: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html#plugins-inputs-http-threads ?
