### ISSUE TITLE
Please add HTTPS

### ISSUE THREAD

**Issue by meganuke19** [moshen/logstash-http-input#5]
Please add HTTPS with certificate checking.
It's needed for  systemd journal-upload.

**Comment by moshen** [comment]
I'll take a look at adding the configuration options.  This has been on the backburner since I've only used this behind a reverse proxy like nginx (which handles the ssl termination).

**Comment by moshen** [comment]
[It looks like there is now an official http input plugin in 1.5.0, that will support SSL](https://github.com/logstash-plugins/logstash-input-http), I probably wont be updating this further.
