### ISSUE TITLE
add support for logstash 1.5

### ISSUE THREAD

**Issue by Vlad777** [moshen/logstash-http-input#7]
Latest beta version of logstash 1.5 changed how contrib plugins are managed. Would like to try this awesome http plugin with new version 1.5. Thank you.

**Comment by moshen** [comment]
Thanks for the heads up, I'll see if I can adapt the build

**Comment by orrery** [comment]
Hi Moshen, I followed the build instructions and I have logstash 1.5 but when running log stash it's reporting :

```Couldn't find any input plugin named 'http'. Are you sure this is correct? Trying to load the http input plugin resulted in this error: no such file to load -- logstash/inputs/http```

Can you provide any advice?

**Comment by kelvinfann** [comment]
Just verifying, support hasn't been added yet has it?

**Comment by moshen** [comment]
No, sorry.  [Since it looks like there is now an official http input plugin in 1.5.0](https://github.com/logstash-plugins/logstash-input-http), I probably wont be updating this further.
