### ISSUE TITLE
multiline support

### ISSUE THREAD

**Issue by aetheon** [moshen/logstash-http-input#8]
Hi there,

I've been trying to add multiline support to my http input without success. When I try the codec=>line 
is working but I need to make it work with stack traces.

Is the multiline supported with http input? Thanks.

**Comment by moshen** [comment]
Should work.  Does the same multiline pattern work with a file or alternate input?

If you're sending a single log message in a single POST/PUT then you can use the "plain" codec to use the entire body.

**Comment by aetheon** [comment]
@moshen Thanks for the quick reply. I've been trying a few combinations and the only way I found to make it work the following,

```
input { 

    http {
    
        host => "0.0.0.0"
        port => 6000
        maxFormSize => 10485760

        # this is needed to process line by line and therefore get 
        # the multiline behaviour
        codec => line {
            charset => "UTF-8"
        }
    }

filter {

    # This must be the first line because this will stop the processing 
    # if the line is not a log entry
    multiline {
        pattern => "^\["
        what => "previous"
        negate=> true
    }
    grok {
        match => [ 
            "message",
            "(?m)^\[%{TIMESTAMP_ISO8601:timestamp}\] %{GREEDYDATA:message}"
        ]
        overwrite => [ "message" ]
    }

    date {
        match => [ "timestamp" , "YYYY-MM-dd HH:mm:ss:SSS" ]
        locale => "en"
    }

    if "_grokparsefailure" in [tags] {
        drop { }
    }

}

}

```

**Comment by moshen** [comment]
Sorry this has languished for a while, but your solution looks like it would work.  Without seeing an example log, I wont be of much help.  Closing.
