### ISSUE TITLE
build destination folder

### ISSUE THREAD

**Issue by fireflyk** [moshen/logstash-http-input#9]
change plugins/logstash/inputs/http.rb => lib/logstash/inputs/http.rb

**Comment by fireflyk** [comment]
It 's my fault. You use -p plugin start. Ignore the issue.

**Comment by moshen** [comment]
Initially I was dropping the plugin files directly into lib, but I thought it would be a little cleaner (and easier for logstash upgrade) to use the separate plugin path.  Fortunately, logstash is moving to a more dynamic plugin structure for 1.5.0 and I will be (attempting to) update this plugin to work with that structure (see: #7).

**Comment by fireflyk** [comment]
Oh, it 's cool. I see.
